### ISSUE TITLE
Difference between Build and Publish the book

### ISSUE THREAD

**Issue by nilrodes** [UNISvalbard/Geo-UAV#2]
All figures are shown when building the jupyter book, however a few ones are not there when publishing it.

I tried changing name and reducing file size, but it doesn't seem to fix it.

The file path is correct.

The error I get in anaconda prompt is: 
![image](https://github.com/UNISvalbard/Geo-UAV/assets/77401268/36e638a8-99b1-4e22-9e7a-75c79d616fc5)

**Comment by PeterBetlem** [comment]
error found in the message itself.
